#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
i18n.py - Every user-facing string in netmon, in English and Hebrew.

The language comes from LANG in netmon.conf (en | he) and can be switched at
any time from the bot with /setlang. Terminal output of analyze.py stays
English on purpose - it is a diagnostics tool, not a user-facing report.

    from i18n import t
    t("en", "report_title")
    t(lang, "of_plan", 83.0)          # positional %-args, same order in both

Adding a language: copy a block, translate the values, add the code to LANGS.
Missing keys fall back to English rather than crashing a cron job.
"""

LANGS = ("en", "he")

# Right-to-left languages need dir=rtl on the HTML report.
RTL = {"he"}

STRINGS = {
    # ---------------------------------------------------------------- report
    "report_title":     {"en": "Internet quality report",
                         "he": "דוח איכות אינטרנט"},
    "report_meta":      {"en": "%s → %s · ISP: %s · %d measurements (%.0f%% success)",
                         "he": "%s → %s · ספק: %s · %d מדידות (%.0f%% הצלחה)"},
    "verdict_nodata":   {"en": "Not enough samples yet covering both evening and night hours.",
                         "he": "אין עדיין מספיק דגימות שמכסות גם ערב וגם לילה."},
    "verdict_bad":      {"en": "The line chokes in the evening — %.0f%% slower than at night. A classic sign of an oversubscribed shared line.",
                         "he": "הקו נחנק בשעות הערב — ירידה של %.0f%% לעומת הלילה. סימן מובהק לקו משותף עמוס (over-subscription)."},
    "verdict_warn":     {"en": "Noticeable evening congestion — %.0f%% slower than at night.",
                         "he": "עומס מורגש בשעות הערב — ירידה של %.0f%% לעומת הלילה."},
    "verdict_good":     {"en": "The line holds up well at peak hours (only %.0f%% slower).",
                         "he": "הקו יציב יחסית גם בשעות העומס (ירידה של %.0f%% בלבד)."},
    "card_dl":          {"en": "Download (median)", "he": "הורדה (חציון)"},
    "card_ul":          {"en": "Upload (median)",   "he": "העלאה (חציון)"},
    "card_ping":        {"en": "Idle ping",         "he": "פינג idle"},
    "card_bb":          {"en": "Bufferbloat",       "he": "Bufferbloat"},
    "card_loss":        {"en": "Packet loss",       "he": "אובדן חבילות"},
    "card_dl_low":      {"en": "Download low",      "he": "שפל הורדה"},
    "of_plan":          {"en": "%.0f%% of plan",    "he": "%.0f%% מהחבילה"},
    "low10":            {"en": "worst 10%%: %.0f%%", "he": "שפל 10%%: %.0f%%"},
    "median":           {"en": "median",            "he": "חציון"},
    "average":          {"en": "average",           "he": "ממוצע"},
    "chart_dl_title":   {"en": "Average download by hour of day",
                         "he": "מהירות הורדה ממוצעת לפי שעה ביום"},
    "chart_dl_cap":     {"en": "Red = below 60%% of plan. Dashed line = the speed you pay for. Hover a bar for details.",
                         "he": "אדום = מתחת ל‑60%% מהחבילה. הקו המקווקו = מהירות החבילה. מרחפים על עמודה לפרטים."},
    "chart_bb_title":   {"en": "Bufferbloat (added latency under load) by hour",
                         "he": "Bufferbloat (עליית השהיה תחת עומס) לפי שעה"},
    "chart_bb_cap":     {"en": "Red = above 80ms. High values in the evening mean the line is saturated with no queue management (QoS).",
                         "he": "אדום = מעל 80ms. ערכים גבוהים בשעות הערב = הקו נחנק ואין ניהול תור/QoS."},
    "plan_label":       {"en": "plan",              "he": "חבילה"},
    "night_label":      {"en": "Night (%02d–%02d): <b>%.0f</b> Mbps",
                         "he": "לילה (%02d–%02d): <b>%.0f</b> Mbps"},
    "evening_label":    {"en": "Evening (%02d–%02d): <b style='color:%s'>%.0f</b> Mbps",
                         "he": "ערב (%02d–%02d): <b style='color:%s'>%.0f</b> Mbps"},
    "worst_title":      {"en": "Worst events",      "he": "האירועים הגרועים ביותר"},
    "col_time":         {"en": "Time",     "he": "זמן"},
    "col_download":     {"en": "Download", "he": "הורדה"},
    "col_ping":         {"en": "Ping",     "he": "פינג"},
    "col_loss":         {"en": "Loss",     "he": "אובדן"},
    "report_footer":    {"en": "Generated by netmon · %d samples total (%d failed).",
                         "he": "הופק אוטומטית ע\"י netmon · %d דגימות סה\"כ (%d כשלו)."},
    "summary_title":    {"en": "Internet quality report", "he": "דוח איכות אינטרנט"},
    "summary_dl":       {"en": "Download (median): <b>%.0f Mbps</b>%s",
                         "he": "הורדה (חציון): <b>%.0f Mbps</b>%s"},
    "summary_ul_ping":  {"en": "Upload: %.0f Mbps · Ping: %.0f ms",
                         "he": "העלאה: %.0f Mbps · פינג: %.0f ms"},
    "summary_bb_loss":  {"en": "Bufferbloat: %.0f ms · Loss: %.1f%%",
                         "he": "Bufferbloat: %.0f ms · אובדן: %.1f%%"},
    "summary_night_day": {"en": "Night %.0f → evening %.0f Mbps",
                          "he": "לילה %.0f → ערב %.0f Mbps"},
    "summary_count":    {"en": "%d measurements · %.0f%% success",
                         "he": "%d מדידות · %.0f%% הצלחה"},
    "summary_attached": {"en": "\n📎 Full report with charts attached.",
                         "he": "\n📎 הדוח המלא עם גרפים מצורף כקובץ."},
    "report_caption":   {"en": "Internet quality report", "he": "דוח איכות אינטרנט מצורף"},

    # ---------------------------------------------------------------- alerts
    "alert_slow":       {"en": "⚠️ <b>Slow line</b>\nDownload %.0f Mbps — only %.0f%% of your %.0f Mbps plan.\nPing %s ms · bufferbloat %s ms · loss %s%%",
                         "he": "⚠️ <b>הקו איטי</b>\nהורדה %.0f Mbps — רק %.0f%% מהחבילה שלך (%.0f Mbps).\nפינג %s ms · bufferbloat %s ms · אובדן %s%%"},
    "alert_failed":     {"en": "🔴 <b>Measurement failed</b>\n%s\nThe line may be down entirely.",
                         "he": "🔴 <b>המדידה נכשלה</b>\n%s\nייתכן שהקו נפל לגמרי."},

    # ------------------------------------------------------------------- bot
    "bot_online":       {"en": "✅ netmon bot is online. Send /help for commands.",
                         "he": "✅ בוט netmon באוויר. שלח /help לרשימת הפקודות."},
    "bot_help":         {"en": ("📡 <b>netmon — internet quality monitor</b>\n\n"
                                "<b>Measure</b>\n"
                                "/speed — run a measurement right now\n"
                                "/stats — summary of the data so far\n"
                                "/report — build the HTML report and send it here\n\n"
                                "<b>Monitoring</b>\n"
                                "/status — is monitoring running, and the last result\n"
                                "/pause — stop automatic measurements\n"
                                "/resume — start them again\n\n"
                                "<b>Settings</b>\n"
                                "/config — show all current settings\n"
                                "/setplan &lt;down&gt; [up] — the speed your ISP sells you, Mbps\n"
                                "/setinterval &lt;minutes&gt; — time between measurements (5–1440)\n"
                                "/setalert &lt;percent&gt;|off — instant alert below this %% of plan\n"
                                "/setreport &lt;day&gt; &lt;hour&gt;|off — periodic report (day 0=Sun)\n"
                                "/setping &lt;host&gt; — baseline ping target\n"
                                "/calibrate — find which server represents your line\n"
                                "/setserver &lt;id&gt;|auto — measure against a specific server\n"
                                "/setlang en|he — language\n"
                                "/help — this message"),
                         "he": ("📡 <b>netmon — ניטור איכות אינטרנט</b>\n\n"
                                "<b>מדידה</b>\n"
                                "/speed — מדידה עכשיו\n"
                                "/stats — סיכום הנתונים שנאספו\n"
                                "/report — בניית דוח HTML ושליחתו לכאן\n\n"
                                "<b>ניטור</b>\n"
                                "/status — האם הניטור פעיל והמדידה האחרונה\n"
                                "/pause — עצירת המדידות האוטומטיות\n"
                                "/resume — החזרתן\n\n"
                                "<b>הגדרות</b>\n"
                                "/config — כל ההגדרות הנוכחיות\n"
                                "/setplan &lt;הורדה&gt; [העלאה] — המהירות שאתה משלם עליה, Mbps\n"
                                "/setinterval &lt;דקות&gt; — כל כמה זמן למדוד (5–1440)\n"
                                "/setalert &lt;אחוז&gt;|off — התראה מיידית מתחת לאחוז זה מהחבילה\n"
                                "/setreport &lt;יום&gt; &lt;שעה&gt;|off — דוח תקופתי (יום 0=ראשון)\n"
                                "/setping &lt;כתובת&gt; — יעד הפינג הבסיסי\n"
                                "/calibrate — איתור השרת שמייצג את הקו שלך\n"
                                "/setserver &lt;מזהה&gt;|auto — מדידה מול שרת מסוים\n"
                                "/setlang en|he — שפה\n"
                                "/help — ההודעה הזו")},
    "bot_measuring":    {"en": "⏳ Measuring… this takes about 40 seconds.",
                         "he": "⏳ מודד… זה לוקח כ‑40 שניות."},
    "bot_measure_ok":   {"en": "📡 <b>Measurement</b>\n%s",
                         "he": "📡 <b>מדידה</b>\n%s"},
    "bot_measure_fail": {"en": "❌ Measurement failed:\n%s",
                         "he": "❌ המדידה נכשלה:\n%s"},
    "bot_paused_manual": {"en": ("⏸ Automatic monitoring is paused — running this one "
                                 "anyway because you asked. /resume to restart the schedule."),
                          "he": ("⏸ הניטור האוטומטי עצור — מריץ את המדידה הזו בכל זאת "
                                 "כי ביקשת. /resume כדי להחזיר את התזמון.")},
    "bot_calibrating":  {"en": ("🎯 Testing %d nearby servers to find which one represents "
                                "your line. This transfers a few GB and takes a few minutes."),
                         "he": ("🎯 בודק %d שרתים קרובים כדי למצוא מי מהם מייצג את הקו שלך. "
                                "זה מעביר כמה ג׳יגה ולוקח כמה דקות.")},
    "bot_calibrated":   {"en": "🎯 <b>Calibration</b>\n%s",
                         "he": "🎯 <b>כיול</b>\n%s"},
    "bot_calibrate_fail": {"en": "❌ Calibration failed:\n%s",
                           "he": "❌ הכיול נכשל:\n%s"},
    "bot_building":     {"en": "📊 Building the report…", "he": "📊 בונה את הדוח…"},
    "bot_report_fail":  {"en": "❌ Report failed:\n%s",    "he": "❌ שגיאה בדוח:\n%s"},
    "bot_status":       {"en": ("📡 <b>Monitor status</b>\n\n"
                                "Automatic measurements: %s\n"
                                "Every: %d min\n"
                                "Scheduler (cron): %s\n"
                                "Last measurement: %s\n"
                                "Samples collected: %d"),
                         "he": ("📡 <b>מצב הניטור</b>\n\n"
                                "מדידות אוטומטיות: %s\n"
                                "כל: %d דקות\n"
                                "מתזמן (cron): %s\n"
                                "מדידה אחרונה: %s\n"
                                "דגימות שנאספו: %d")},
    "state_running":    {"en": "▶️ running",  "he": "▶️ פעיל"},
    "state_paused":     {"en": "⏸️ paused",   "he": "⏸️ מושהה"},
    "no_data_yet":      {"en": "no measurements yet", "he": "אין מדידות עדיין"},
    "bot_paused":       {"en": "⏸️ Automatic measurements paused. Resume with /resume.",
                         "he": "⏸️ המדידות האוטומטיות הושהו. להפעלה: /resume"},
    "bot_resumed":      {"en": "▶️ Automatic measurements resumed. Next one runs on schedule; for an immediate check use /speed.",
                         "he": "▶️ המדידות האוטומטיות חזרו. הבאה תרוץ לפי הלו\"ז; לבדיקה מיידית: /speed"},
    "bot_config":       {"en": "⚙️ <b>Settings</b>\n\n%s\n\nChange them with the /set… commands (/help).",
                         "he": "⚙️ <b>הגדרות</b>\n\n%s\n\nלשינוי: פקודות /set… (ראה /help)"},
    "bot_saved":        {"en": "✅ Saved: %s",  "he": "✅ נשמר: %s"},
    "bot_bad_value":    {"en": "❌ %s: %s",     "he": "❌ %s: %s"},
    "bot_usage":        {"en": "Usage: %s",     "he": "שימוש: %s"},
    "bot_unknown":      {"en": "Unknown command. /help shows what I can do.",
                         "he": "פקודה לא מוכרת. /help מציג את מה שאני יודע לעשות."},
    "bot_busy":         {"en": "⏳ Already working on a measurement, one moment.",
                         "he": "⏳ כבר רץ תהליך מדידה, רגע."},
    "bot_schedule_set": {"en": "✅ Schedule updated:\n<code>%s</code>",
                         "he": "✅ הלו\"ז עודכן:\n<code>%s</code>"},
    "bot_schedule_err": {"en": "⚠️ Saved, but the schedule could not be written to cron: %s",
                         "he": "⚠️ נשמר, אך לא ניתן היה לעדכן את ה‑cron: %s"},
    "bot_alerts_off":   {"en": "🔕 Instant alerts disabled.", "he": "🔕 התראות מיידיות כובו."},
    "bot_report_off":   {"en": "🔕 Periodic report disabled.", "he": "🔕 הדוח התקופתי כובה."},
    "bot_stats":        {"en": ("📊 <b>Summary</b> (%d measurements)\n\n"
                                "Download: median <b>%.0f</b> · min %.0f · max %.0f Mbps%s\n"
                                "Upload: median %.0f Mbps\n"
                                "Ping: %.0f ms · bufferbloat %.0f ms · loss %.1f%%\n"
                                "Failed measurements: %d\n%s"),
                         "he": ("📊 <b>סיכום</b> (%d מדידות)\n\n"
                                "הורדה: חציון <b>%.0f</b> · מינ' %.0f · מקס' %.0f Mbps%s\n"
                                "העלאה: חציון %.0f Mbps\n"
                                "פינג: %.0f ms · bufferbloat %.0f ms · אובדן %.1f%%\n"
                                "מדידות שנכשלו: %d\n%s")},
    "bot_no_data":      {"en": "No measurements yet. Run /speed for the first one.",
                         "he": "אין עדיין מדידות. הרץ /speed לראשונה."},
}


def t(lang, key, *args):
    """Translate `key` into `lang`, falling back to English then to the key itself."""
    entry = STRINGS.get(key)
    if not entry:
        return key
    s = entry.get(lang) or entry.get("en") or key
    if args:
        try:
            return s % args
        except (TypeError, ValueError):
            return s
    # No args: the string is still written with %%-escaping so that adding an
    # argument later cannot silently break it. Unescape it here.
    return s.replace("%%", "%")


def direction(lang):
    return "rtl" if lang in RTL else "ltr"
